# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c062033015b622bf178fdda9d9ec5791c5ca87fedfd5f56da8febbeebec9704e838188cced3d453d6023917eee84e69c047c2595c31cb9e72ceb7a5d22035ab

test:
  secret_key_base: 616037de1520691817d2cd0cbcd7eeb823c5fdec31ea9940a43a2d21d8aae0e5fa8a76a41a4d1ba079b9da078464eb07230181dc7346498452658937180122d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
